### ISSUE TITLE
Expose Armor VS a 5 stack of sunder armor feature request.

### ISSUE THREAD

**Issue by Dtain11** [oratory/zug#1]
Would it be possible to show the gain of expose over a 5 stack of sunder armor. Basically just another line such as:

Expose Armor was active for 85% of physical attacks:
This contributed to 509,259 damage (7,964 DPS).
This contributed to 25,462 damage ( 398.4 DPS) more than a 5 stack of sunder armor would have. 

Math is rounded above for example purposes. I think this would give a quick glance at the true Value of EA vs a full DPS.

**Comment by oratory** [comment]
Added in https://github.com/oratory/zug/commit/f23e1500b05e91dda4aac135c01352f66787eb54
