### ISSUE TITLE
Tool not able to pull log

### ISSUE THREAD

**Issue by jgoldring** [oratory/zug#3]
Hi there, I've been using this wonderful tool since I found out about it. Over the last two weeks I've noticed it is unable to pull reports. When you input a log URL, it presents the dropdown to select an encounter, but no data is present.

The error is:
`GET https://zugz.ug/api/report?id=<id> 500`
`TypeError: Cannot read property 'report' of undefined`
    `at o.<anonymous> (LogViewer.vue:57)`
    `at u (runtime.js:63)`
    `at Generator._invoke (runtime.js:293)`
    `at Generator.next (runtime.js:118)`
   `at o (asyncToGenerator.js:3)`
    `at s (asyncToGenerator.js:25)`

**Comment by oratory** [comment]
Not sure what the issue was but restarting the server seems to have fixed it.
